//
// CafeResult.swift
// CafeBlogExampleTests
//
// Created by 조선미 on 2021/07/19.
//

import Foundation

@testable import CafeBlogExample

struct CafeResultDummy {
    let cafeResultDummy = PostResponse(meta: Meta(totalCount: 3340210, pageableCount: 546, isEnd: false),
                                       documents: CafeDummyData().cafeResultDummy)
}

extension CafeResultDummy {
    struct CafeDummyData {
        let cafeResultDummy: [Post] = [
            Post(title: "<b>고양이</b> 집사들이 한번쯤 꼭 찍고싶어 하는 사진", contents: "출처 : 여성시대 누가봐도 INFP 그것은 바로바로 <b>고양이</b> 하품샷! 잘 찍으면 이렇게 시원시원한 하품샷이 나오지만 타이밍이 조금이라도 어긋난다면.... 무서운 표정이...", url: "http://cafe.daum.net/subdued20club/ReHf/3359952", blogName: nil, cafeName: "＊여성시대＊ 차분한 20대들의 알흠다운 공간", thumbnailURL: "https://search2.kakaocdn.net/argon/130x130_85_c/EgtwqAJXsa6", datetime: Date()),
            Post(title: "🐱<b>고양이</b> 만쥬🐱", contents: "づ⌁⌁⌁❤︎⌁⌁⌁⋆ 몸과 마음의 양식...? 나 순간 책인줄 알고 응????? 했는데 열어보니 <b>고양이</b> 만쥬 였잔아!!!!!!!!!! 이거슴 바로바로!!! 워녕이 생일 기념 무나였던 !! 원영...", url: "http://cafe.daum.net/baemilytory/BzUs/195127", blogName: nil, cafeName: "밀리토리네", thumbnailURL: "https://search3.kakaocdn.net/argon/130x130_85_c/8PhkUhReBUe", datetime: Date()),
            Post(title: "유기견&#39; 이어 ‘사지 절단된 새끼<b>고양이</b>’ 대구서 발견", contents: "057/0001581699?cds=news_edit &#39;두 눈 파인 유기견&#39; 이어 ‘사지 절단된 새끼<b>고양이</b>’ 대구서 발견 경기 안성에서 ‘두 눈이 파인 개’가 발견된 데 이어, 이번엔 대구...", url: "http://cafe.daum.net/SoulDresser/FLTB/413882", blogName: nil, cafeName: "소울드레서 (SoulDresser)", thumbnailURL: "", datetime: Date()),
            Post(title: "나는 법을 가르쳐준 <b>고양이</b>》깜짝 출부 2탄 입니다😄✈", contents: "아드리한테 장문의 편지를 보내줬습니다. 《갈매기에게 나는 법을 가르쳐준 <b>고양이</b>》 제가 좋아하는 책이기도하고 지난 주 6학년 아이들 수업한 책 입니다. 아드리가...", url: "http://cafe.daum.net/SkyEagle/JtOD/631", blogName: nil, cafeName: "부모님과 곰신을 위한 공군가족", thumbnailURL: "https://search3.kakaocdn.net/argon/130x130_85_c/5pq3QNpR42V", datetime: Date()),
            Post(title: "잘해줘야해 - <b>고양이</b>♡까마귀 편 (+<b>고양이</b> 사진 첨부...", contents: "물까치 vs 까마귀를 재밌어 해서 놀랬어 ㅋㅋㅋㅋㅋㅋㅋ 쨌뜬 그래서 써보는 <b>고양이</b>♡까마귀 편! 2. 까마귀 내니 까마귀들에게 조공을 하고 한달정도 됐을거야 얘들이...", url: "http://cafe.daum.net/subdued20club/VETW/45560", blogName: nil, cafeName: "＊여성시대＊ 차분한 20대들의 알흠다운 공간", thumbnailURL: "https://search4.kakaocdn.net/argon/130x130_85_c/JxxoQoxWg8d", datetime: Date()),
            Post(title: "길고양이에 먹이 금지? <b>고양이</b>는 싫고 쥐들을 원하나”", contents: "함께 &#34;먹이를 주지 말라고 야생동물은 병균을 옮긴다고 써 붙여 놓으셨다&#34;며 &#34;<b>고양이</b>는 싫고 쥐들을 원하나 쥐 득실 득실을 몹시 원하는 건가 아닐 것 같은데&#34;라고 불편...", url: "http://cafe.daum.net/dotax/Elgq/3670135", blogName: nil, cafeName: "도탁스 (DOTAX)", thumbnailURL: "https://search1.kakaocdn.net/argon/130x130_85_c/E5M0Sbg2p3Z", datetime: Date()),
            Post(title: "아기 <b>고양이</b>를 냥줍한 당신을 위한 글", contents: "출처 : 여성시대 부자가될여시야 나는 며칠 전에 길에서 냥줍을 경험한 여시야 <b>고양이</b>의 고 자도 잘 모르는데 뜬금없이 간택을 당하는 바람에 여시에서 도움도 많이...", url: "http://cafe.daum.net/subdued20club/LxCT/291835", blogName: nil, cafeName: "＊여성시대＊ 차분한 20대들의 알흠다운 공간", thumbnailURL: "https://search2.kakaocdn.net/argon/130x130_85_c/4q6EPK1RXzB", datetime: Date()),
            Post(title: "온 몸이 난도질 된 <b>고양이</b>가 발견되었어 (사진 주의) +추가", contents: "단체 케어 인스타그램 [긴급구조] 온 몸이 난도질 돼 있는 <b>고양이</b> “대체 누가 그런 거니?” 학대당한 <b>고양이</b>가 길거리에서 울고 있다는 제보. 사진으로 보기에도 온몸...", url: "http://cafe.daum.net/ok1221/9Zdf/2410335", blogName: nil, cafeName: "쭉빵카페", thumbnailURL: "https://search1.kakaocdn.net/argon/130x130_85_c/JyxJKTNMuPK", datetime: Date()),
            Post(title: "🌱 SF9 달글 🌱 도봉산 산<b>고양이</b> 🐱 탄생일 🎂 #5월_11일에...", contents: "➴➵➶➴➵➶➴➵➶➴➵➶➴➵➶ Happy Birthday HY 0:00 ──────💗── 05:11 ⇄ ◀▶ ↻ ➴➵➶➴➵➶➴➵➶➴➵➶➴➵➶ Volume: ▁▂▃▄▅▆▇▉ ╭━━━━━━━━━╮ 오늘 규니 생일...", url: "http://cafe.daum.net/baemilytory/9Nwb/1069", blogName: nil, cafeName: "밀리토리네", thumbnailURL: "https://search3.kakaocdn.net/argon/130x130_85_c/7OezKcEU1c3", datetime: Date()),
            Post(title: "갖고있는 <b>고양이</b> 이모티콘 자랑해보자", contents: "게시글엔 이모티콘이 등록이 안돼서 댓글로 달겠음", url: "http://cafe.daum.net/Tlwkftlqkftlldlqkf/8vJr/149947", blogName: nil, cafeName: "우리 동네 목욕탕", thumbnailURL: "https://search1.kakaocdn.net/argon/130x130_85_c/903BWYAHhov", datetime: Date()),
            Post(title: "<b>고양이</b> 시체 치우고 왔음...(텍혐주의)", contents: "출처 : 여성시대 딱대 식당알바 해봤는데 식기세척기 대부분이 저런구조고 들어갈꺼라 당근 상상도 못했을 것.... 글쓴이 착한 사람임 글쓴이 욕 지양부탁", url: "http://cafe.daum.net/subdued20club/RaxJ/97749", blogName: nil, cafeName: "＊여성시대＊ 차분한 20대들의 알흠다운 공간", thumbnailURL: "https://search3.kakaocdn.net/argon/130x130_85_c/KEVj8Kdcf7a", datetime: Date()),
            Post(title: "<b>고양이</b>가 이만큼 방충망을 찢고 나갈수가 있어??", contents: "우리집 1층이고 손 가르킨부분까지 찢어져서 나 외출간 사이에 탈출했어.. 방금 한시간가량 찾고왔는데도 안보여..진짜 죽고싶다 집에 하루종일 있었던 애비새끼는...", url: "http://cafe.daum.net/Tlwkftlqkftlldlqkf/919A/3878394", blogName: nil, cafeName: "우리 동네 목욕탕", thumbnailURL: "", datetime: Date()),
            Post(title: "론쏭이랑 밤 282알째 까는 중🌰 💕아기<b>고양이</b>의 생일날 💕", contents: "나의 천추의 한이란다..지칠 때 들으면 힘나는 노래 바로 맘마미아..이 귀염잔망 <b>고양이</b>를 실제로 못보다니 하 넌 어쩜 이렇게 사랑스럽니 맘마미아같은 노래도 한번 더...", url: "http://cafe.daum.net/Duckgu/D2nu/25767", blogName: nil, cafeName: "방석 위로 모여라", thumbnailURL: "https://search2.kakaocdn.net/argon/130x130_85_c/4DLDNB2Hqgz", datetime: Date()),
            Post(title: "새까매서 눈만 보이는 게 매력인 검정 <b>고양이</b>", contents: "문제 시 <b>고양이</b> 간식주러 감", url: "http://cafe.daum.net/wm1221/D3Pd/2736", blogName: nil, cafeName: "성공회의소", thumbnailURL: "https://search3.kakaocdn.net/argon/130x130_85_c/1nUPjc9VgCb", datetime: Date()),
            Post(title: "강아지,<b>고양이</b> 키우지 마", contents: "갑자기 강아지, <b>고양이</b> 키우지 말라는 글 당황스럽지? 나는 강아지를 키우고 있는 보호자야 그런데 우연히 반려동물 시장이 점점 커지고 있고 반려동물을 키우는 인구도...", url: "http://cafe.daum.net/ok1221/9fQk/156482", blogName: nil, cafeName: "쭉빵카페", thumbnailURL: "https://search1.kakaocdn.net/argon/130x130_85_c/FnRB52PnRPv", datetime: Date()),
            Post(title: "[냥귀염] <b>고양이</b>한테 벨 누르면 간식주는거 가르치는 중", contents: "다음카페 밀리토리네 [신문보는 밀리] 허락댓 클릭 시 원글 이동", url: "http://cafe.daum.net/baemilytory/91cd/336304", blogName: nil, cafeName: "밀리토리네", thumbnailURL: "https://search4.kakaocdn.net/argon/130x130_85_c/25COR6rZVDE", datetime: Date()),
            Post(title: "냥모형에게 <b>고양이</b> 알레르기가 있다고 하면 반응이...", contents: "그만 알아보자😑", url: "http://cafe.daum.net/cravity-official/9KXO/137", blogName: nil, cafeName: "크래비티(CRAVITY) 공식 팬카페", thumbnailURL: "https://search1.kakaocdn.net/argon/130x130_85_c/HKUEZPubC0A", datetime: Date()),
            Post(title: "<b>고양이</b> 그려드립니다", contents: "요런식으로 대충", url: "http://cafe.daum.net/baemilytory/8zMg/894512", blogName: nil, cafeName: "밀리토리네", thumbnailURL: "https://search2.kakaocdn.net/argon/130x130_85_c/GTAp9M2DPlG", datetime: Date()),
            Post(title: "길에서 살기힘든 온순한 <b>고양이</b> 감자의 정회원 구조동의...", contents: "열흘 전에 학교를 다녀오던 여고생(황예은양)이 길에서 우연히 <b>고양이</b>를 발견했는데, 이 <b>고양이</b>가 자기를 보자마자 야옹야옹하며 가까이 다가와서 부비부비하자 가엾은...", url: "http://cafe.daum.net/T-PJT/Pbsz/633", blogName: nil, cafeName: "팅커벨 프로젝트", thumbnailURL: "https://search2.kakaocdn.net/argon/130x130_85_c/5YYlKv8qEwd", datetime: Date()),
            Post(title: "책상위에 <b>고양이</b>🐱", contents: "!안농! 제 책상위에 <b>고양이</b>가 있는데 이 <b>고양이</b> 이름은 뭘까요..? ㅎㅅㅎ 헬멧에 비비라고 적혀있는데 비비인가?🧐 ㅋㅋㅋ <b>고양이</b> 너무 귀여워요 표정이 어디라도 질주...", url: "http://cafe.daum.net/OmegaX/CYwx/326", blogName: nil, cafeName: "OMEGA X 공식 팬카페", thumbnailURL: "https://search1.kakaocdn.net/argon/130x130_85_c/CYM8FeYXHDZ", datetime: Date()),
            Post(title: "<b>고양이</b> 아직 살아있어요.ㅠㅠ 기도좀해주실래요?", contents: "어제 저녁에 딸아이 기숙사로 복귀시켜주러 나가는데 저 위에 <b>고양이</b> 두마리가 보이는거에요 흰둥이 한마리는 누워있고 고등어는 앉아서 흰둥이를 쳐다보고있고 한참을...", url: "http://cafe.daum.net/10in10/1pRl/1286242", blogName: nil, cafeName: "텐인텐[10년 10억 만들기]", thumbnailURL: "", datetime: Date()),
            Post(title: "아파트 단지내에 <b>고양이</b> 집을 지은 캣맘들", contents: "아파트 단지 내의 길고양이들을 돌보기 위해 화단 한 편에 <b>고양이</b> 집을 지은 캣맘들. <b>고양이</b>들은 더이상 잠자리와 먹이 때문에 서로 싸우지 않아도 되고, <b>고양이</b>를...", url: "http://cafe.daum.net/rocksoccer/ADs1/520666", blogName: nil, cafeName: "樂soccer", thumbnailURL: "https://search1.kakaocdn.net/argon/130x130_85_c/xNzYO9F4M5", datetime: Date()),
            Post(title: "[<b>고양이</b> 눈]생명수(동아일보) / [빛viit명상] 생명을...", contents: "[<b>고양이</b> 눈]생명수 출처 동아일보 : https://www.donga.com/news/Opinion/article/all/20210621/107549255/1 금계국 줄기에 빗방울이 은구슬처럼 맺혔습니다. 작은...", url: "http://cafe.daum.net/webucs/8nL6/2542", blogName: nil, cafeName: "사단법인 빛명상", thumbnailURL: "https://search1.kakaocdn.net/argon/130x130_85_c/8vyeOuKt6gD", datetime: Date()),
            Post(title: "잘 키운 내 <b>고양이</b>, 열 남자 안 부럽다.webtoon", contents: "녹녹찮소... 그렇게 노답배틀 후 피곤한 발길을 옮기다 우연히 <b>고양이</b> 소리를 듣게 되는데... oh <b>고양이</b>는 못 참지 ^-^ oh 앗...! 다리를 다친 깜냥이가 털을 바짝...", url: "http://cafe.daum.net/happydalcom-moonpa/XIK5/323", blogName: nil, cafeName: "행복한 달콤씁쓸", thumbnailURL: "https://search4.kakaocdn.net/argon/130x130_85_c/JHzKnlWnrOV", datetime: Date()),
            Post(title: "너 <b>고양이</b>야?", contents: "<b>고양이</b>야🐈❔뭐❓농담이에요🤗너👀<b>고양이</b>야🐈❔뭐❓농담이에요🤗너👀<b>고양이</b>야🐈❔뭐❓농담이에요🤗너👀<b>고양이</b>야🐈❔뭐❓농담이에요🤗너👀<b>고양이</b>야🐈❔뭐❓농담이에요🤗너👀<b>고양이</b>야🐈❔뭐❓농담...", url: "http://cafe.daum.net/Tlwkftlqkftlldlqkf/8vYY/471133", blogName: nil, cafeName: "우리 동네 목욕탕", thumbnailURL: "https://search2.kakaocdn.net/argon/130x130_85_c/Es0ac8wZBFE", datetime: Date()),
            Post(title: "론쏭이랑 밤 282알째 까는 중🌰 💕아기<b>고양이</b>의 생일날 💕", contents: "나의 천추의 한이란다..지칠 때 들으면 힘나는 노래 바로 맘마미아..이 귀염잔망 <b>고양이</b>를 실제로 못보다니 하 넌 어쩜 이렇게 사랑스럽니 맘마미아같은 노래도 한번 더...", url: "http://cafe.daum.net/Duckgu/D2nu/25767", blogName: nil, cafeName: "방석 위로 모여라", thumbnailURL: "https://search2.kakaocdn.net/argon/130x130_85_c/4DLDNB2Hqgz", datetime: Date()),
            Post(title: "새까매서 눈만 보이는 게 매력인 검정 <b>고양이</b>", contents: "문제 시 <b>고양이</b> 간식주러 감", url: "http://cafe.daum.net/wm1221/D3Pd/2736", blogName: nil, cafeName: "성공회의소", thumbnailURL: "https://search3.kakaocdn.net/argon/130x130_85_c/1nUPjc9VgCb", datetime: Date()),
            Post(title: "강아지,<b>고양이</b> 키우지 마", contents: "갑자기 강아지, <b>고양이</b> 키우지 말라는 글 당황스럽지? 나는 강아지를 키우고 있는 보호자야 그런데 우연히 반려동물 시장이 점점 커지고 있고 반려동물을 키우는 인구도...", url: "http://cafe.daum.net/ok1221/9fQk/156482", blogName: nil, cafeName: "쭉빵카페", thumbnailURL: "https://search1.kakaocdn.net/argon/130x130_85_c/FnRB52PnRPv", datetime: Date()),
            Post(title: "[냥귀염] <b>고양이</b>한테 벨 누르면 간식주는거 가르치는 중", contents: "다음카페 밀리토리네 [신문보는 밀리] 허락댓 클릭 시 원글 이동", url: "http://cafe.daum.net/baemilytory/91cd/336304", blogName: nil, cafeName: "밀리토리네", thumbnailURL: "https://search4.kakaocdn.net/argon/130x130_85_c/25COR6rZVDE", datetime: Date()),
            Post(title: "냥모형에게 <b>고양이</b> 알레르기가 있다고 하면 반응이...", contents: "그만 알아보자😑", url: "http://cafe.daum.net/cravity-official/9KXO/137", blogName: nil, cafeName: "크래비티(CRAVITY) 공식 팬카페", thumbnailURL: "https://search1.kakaocdn.net/argon/130x130_85_c/HKUEZPubC0A", datetime: Date()),
            Post(title: "<b>고양이</b> 그려드립니다", contents: "요런식으로 대충", url: "http://cafe.daum.net/baemilytory/8zMg/894512", blogName: nil, cafeName: "밀리토리네", thumbnailURL: "https://search2.kakaocdn.net/argon/130x130_85_c/GTAp9M2DPlG", datetime: Date()),
        ]
    }
}
